/* ============================================================
   script.js — Visitar Guimarães (versão guigui)
   Navegação, animações, validação de formulários e integração
   com a API Flask local (pontos de interesse, pesquisa,
   newsletter, contacto e chatbot com IA).
   ============================================================ */

// Endpoints da API Flask (backend local — correr "python app.py")
const API = {
  places:     'http://localhost:5000/api/places',
  events:     'http://localhost:5000/api/events',
  search:     'http://localhost:5000/api/search',
  contact:    'http://localhost:5000/api/contact',
  newsletter: 'http://localhost:5000/api/newsletter',
  chat:       'http://localhost:5000/api/chat'
};

// Idioma atual (PT/EN), persistido entre visitas
let currentLang = localStorage.getItem('lang') === 'en' ? 'en' : 'pt';

// Mensagens da interface nos dois idiomas (validação, estados, botões)
const MSG = {
  pt: {
    invalidName: 'Introduza o seu nome completo (mínimo 2 caracteres).',
    invalidEmail: 'Introduza um endereço de e-mail válido.',
    invalidSubject: 'Selecione um assunto.',
    invalidMessage: 'A mensagem deve ter pelo menos 10 caracteres.',
    invalidPrivacy: 'Deve aceitar a Política de Privacidade.',
    serverRejected: 'A mensagem não foi aceite pelo servidor.',
    newsDuplicate: 'Este email já está subscrito.',
    newsOk: 'Subscrição confirmada! Obrigado.',
    newsOffline: 'Subscrição registada (modo offline).',
    noResults: 'Sem resultados para a pesquisa.',
    apiOffline: 'API não ligada — a mostrar dados locais.',
    eventDetails: 'Ver detalhes',
    eventDefaultCat: 'Agenda',
    eventNone: 'Sem eventos na data escolhida — veja os destaques da agenda.',
    eventFound: 'Eventos no dia',
    aiLabel: 'Resposta IA',
    aiNote: 'Gerado por inteligência artificial (Google Gemini) — confirme sempre a informação.',
    aiOffline: 'Pesquisa por IA indisponível de momento. Veja os resultados abaixo.',
    linksFound: 'ligação(ões) encontrada(s) para',
    linksNone: 'Nenhuma ligação externa corresponde a',
    showAll: 'Ver todos os pontos de interesse',
    showLess: 'Ver menos pontos de interesse',
    readMore: 'Saber mais',
    thinking: 'A pensar…',
    chatFallback: 'Sou o Guigas! Posso ajudar com turismo, história, gastronomia, eventos e locais a visitar em Guimarães. (IA offline — inicie o servidor com "python app.py".)'
  },
  en: {
    invalidName: 'Enter your full name (at least 2 characters).',
    invalidEmail: 'Enter a valid email address.',
    invalidSubject: 'Select a subject.',
    invalidMessage: 'The message must be at least 10 characters long.',
    invalidPrivacy: 'You must accept the Privacy Policy.',
    serverRejected: 'The message was not accepted by the server.',
    newsDuplicate: 'This email is already subscribed.',
    newsOk: 'Subscription confirmed! Thank you.',
    newsOffline: 'Subscription saved (offline mode).',
    noResults: 'No results for your search.',
    apiOffline: 'API offline — showing local data.',
    eventNone: 'No events on the chosen date — check the agenda highlights.',
    eventFound: 'Events on',
    eventDetails: 'View details',
    eventDefaultCat: 'Agenda',
    aiLabel: 'AI answer',
    aiNote: 'Generated by artificial intelligence (Google Gemini) — always double-check the information.',
    aiOffline: 'AI search unavailable right now. See the results below.',
    linksFound: 'external link(s) found for',
    linksNone: 'No external link matches',
    showAll: 'See all places of interest',
    showLess: 'Show fewer places of interest',
    readMore: 'Learn more',
    thinking: 'Thinking…',
    chatFallback: 'I am Guigas! I can help with tourism, history, gastronomy, events and places to visit in Guimarães. (AI offline — start the server with "python app.py".)'
  }
};
// Atalho: devolve a mensagem no idioma atual
const L = (chave) => MSG[currentLang][chave];

// Barra de navegação: ganha fundo sólido ao fazer scroll; mostra o botão "voltar ao topo"
const navbar = document.getElementById('navbar');
const backToTop = document.getElementById('backToTop');

window.addEventListener('scroll', () => {
  if (window.scrollY > 60) {
    navbar.classList.add('scrolled');
  } else {
    navbar.classList.remove('scrolled');
  }
  if (window.scrollY > 400) {
    backToTop.classList.add('visible');
  } else {
    backToTop.classList.remove('visible');
  }
});

// Menu móvel (hambúrguer): abre/fecha e fecha ao escolher uma ligação
const hamburger = document.getElementById('hamburger');
const mobileMenu = document.getElementById('mobileMenu');

hamburger.addEventListener('click', () => {
  mobileMenu.classList.toggle('open');
});

mobileMenu.querySelectorAll('a').forEach(link => {
  link.addEventListener('click', () => mobileMenu.classList.remove('open'));
});

// Scroll suave para as âncoras internas (compensa a altura da navbar fixa)
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
  anchor.addEventListener('click', function (e) {
    const target = document.querySelector(this.getAttribute('href'));
    if (target) {
      e.preventDefault();
      const offset = 80;
      window.scrollTo({ top: target.offsetTop - offset, behavior: 'smooth' });
    }
  });
});

// Animações de entrada: os elementos aparecem em fade-in quando entram no ecrã
const observerOptions = { threshold: 0.12, rootMargin: '0px 0px -40px 0px' };
const observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
      observer.unobserve(entry.target);
    }
  });
}, observerOptions);

document.querySelectorAll('.card, .activity-card, .food-card, .event-card, .hotel-card, .info-block, .stat-item, .historia-item, .galeria-item, .ligacao-card').forEach(el => {
  el.classList.add('fade-in');
  observer.observe(el);
});

// Newsletter — envia a subscrição à API Flask (POST /api/newsletter);
// se a API estiver offline, confirma localmente como fallback
document.querySelector('.newsletter-form')?.addEventListener('submit', async (e) => {
  e.preventDefault();
  const input = e.target.querySelector('input');
  const status = document.getElementById('newsletterStatus');
  const diz = (msg) => { if (status) status.textContent = msg; else alert(msg); };
  if (!input.value || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(input.value.trim())) return;
  try {
    const r = await fetch(API.newsletter, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: input.value.trim() })
    });
    const data = await r.json();
    if (r.status === 409 || data.duplicate) { diz(L('newsDuplicate')); return; }
    if (!r.ok) throw new Error('API ' + r.status);
    input.value = '';
    diz(L('newsOk'));
  } catch (_) {
    // API offline — regista localmente para não perder a interação
    input.value = '';
    diz(L('newsOffline'));
  }
});

// Formulário de Contacto – validação com JavaScript puro
const contactoForm = document.getElementById('contactoForm');
if (contactoForm) {
  const rules = {
    'cf-nome':       { el: null, err: null, validate: v => v.trim().length >= 2 ? '' : L('invalidName') },
    'cf-email':      { el: null, err: null, validate: v => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim()) ? '' : L('invalidEmail') },
    'cf-assunto':    { el: null, err: null, validate: v => v !== '' ? '' : L('invalidSubject') },
    'cf-mensagem':   { el: null, err: null, validate: v => v.trim().length >= 10 ? '' : L('invalidMessage') },
    'cf-privacidade':{ el: null, err: null, validate: (_, el) => el.checked ? '' : L('invalidPrivacy') },
  };

  Object.keys(rules).forEach(id => {
    rules[id].el  = document.getElementById(id);
    rules[id].err = document.getElementById('err-' + id.replace('cf-', ''));
  });

  // Valida um campo, mostra/limpa a mensagem de erro e devolve se é válido
  function validateField(id) {
    const { el, err, validate } = rules[id];
    const msg = validate(el.value, el);
    err.textContent = msg;
    el.classList.toggle('invalid', msg !== '');
    return msg === '';
  }

  // Valida ao sair do campo (blur) e revalida enquanto o utilizador corrige
  Object.keys(rules).forEach(id => {
    rules[id].el.addEventListener('blur', () => validateField(id));
    rules[id].el.addEventListener('input', () => {
      if (rules[id].el.classList.contains('invalid')) validateField(id);
    });
  });

  contactoForm.addEventListener('submit', async e => {
    e.preventDefault();
    const allValid = Object.keys(rules).map(id => validateField(id)).every(Boolean);
    if (!allValid) {
      // Faz scroll até ao primeiro campo inválido
      const firstInvalid = contactoForm.querySelector('.invalid');
      if (firstInvalid) firstInvalid.scrollIntoView({ behavior: 'smooth', block: 'center' });
      return;
    }
    // Envia a mensagem ao backend (POST /api/contact — validação/moderação no servidor);
    // se a API estiver offline, mantém a confirmação local
    const payload = {
      name: rules['cf-nome'].el.value,
      email: rules['cf-email'].el.value,
      subject: rules['cf-assunto'].el.value,
      message: rules['cf-mensagem'].el.value
    };
    let aceite = true;
    try {
      const r = await fetch(API.contact, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await r.json().catch(() => ({}));
      if (!r.ok && data && data.errors) {
        // O backend recusou (validação/moderação) — mostra o motivo no primeiro erro
        aceite = false;
        const err = document.getElementById('err-mensagem');
        if (err) err.textContent = data.reason || L('serverRejected');
      }
    } catch (_) { /* API offline — segue com confirmação local */ }
    if (!aceite) return;
    contactoForm.reset();
    Object.keys(rules).forEach(id => rules[id].el.classList.remove('invalid'));
    const success = document.getElementById('formSuccess');
    success.classList.add('visible');
    success.scrollIntoView({ behavior: 'smooth', block: 'center' });
    setTimeout(() => success.classList.remove('visible'), 6000);
  });
}

/* ============================================================
   PONTOS DE INTERESSE — grelha dinâmica via API Flask
   (GET /api/places, com lista local de reserva se offline)
   ============================================================ */

// Lista local usada quando a API não está disponível (mesmos 12 pontos da BD)
const FALLBACK_PLACES = [
  { category: 'Palácios',         title: 'Paço dos Duques de Bragança',  image_class: 'image-paco-duques',      badge: 'Imperdível', link: 'https://pacodosduques.gov.pt/', description: 'Construído no século XV pelo 1.º Duque de Bragança, é um dos palácios medievais mais marcantes de Portugal.' },
  { category: 'Monumentos',       title: 'Castelo de Guimarães',         image_class: 'image-castelo-guimaraes', badge: null, link: 'https://pacodosduques.gov.pt/monumentos/castelo-de-guimaraes/', description: 'Símbolo da fundação de Portugal e um dos monumentos mais icónicos da cidade.' },
  { category: 'Centro Histórico', title: 'Centro Histórico',             image_class: 'image-centro-historico',  badge: 'UNESCO', link: 'https://unescoportugal.mne.gov.pt/pt/temas/proteger-o-nosso-patrimonio-e-promover-a-criatividade/patrimonio-mundial-em-portugal/centro-historico-de-guimaraes', description: 'Ruas medievais, praças animadas e um ambiente único que convida a explorar a pé.' },
  { category: 'Igrejas',          title: 'Igreja da Oliveira',           image_class: 'image-igreja-oliveira',   badge: null, link: 'https://pt.wikipedia.org/wiki/Categoria:Igrejas_em_Guimar%C3%A3es', description: 'Um dos marcos religiosos e históricos mais importantes do coração da cidade.' },
  { category: 'Museus',           title: 'Museu Martins Sarmento',       image_class: 'image-museu-martins',     badge: null, link: 'https://www.museusemonumentos.pt/pt/museus-e-monumentos', description: 'Coleção arqueológica de referência para conhecer melhor a herança castreja e romana da região.' },
  { category: 'Natureza',         title: 'Serra da Penha',               image_class: 'image-serra-penha',       badge: null, link: 'https://www.penhaguimaraes.com/pt/', description: 'Suba de teleférico ou a pé e descubra uma das melhores vistas panorâmicas sobre Guimarães.' },
  { category: 'Museus',           title: 'Museu Alberto Sampaio',        image_class: 'image-museu-alberto',     badge: null, link: 'https://www.museusemonumentos.pt/pt/museus-e-monumentos', description: 'Instalado no antigo convento da Colegiada, alberga peças de ourivesaria, escultura e têxteis medievais.' },
  { category: 'Museus',           title: 'Centro Internacional das Artes José de Guimarães', image_class: 'image-ciajg', badge: null, link: 'https://www.ciajg.pt/sobre/', description: 'Inaugurado em 2012 na Plataforma das Artes e da Criatividade, dedica-se à arte contemporânea e à coleção do artista José de Guimarães.' },
  { category: 'Monumentos',       title: 'Muralhas Medievais',           image_class: 'image-muralhas',          badge: null, link: 'http://www.monumentos.gov.pt/site/app_pagesuser/SIPA.aspx?id=1048', description: 'Troços das antigas muralhas que cercavam a cidade medieval, testemunhas silenciosas de séculos de história.' },
  { category: 'Igrejas',          title: 'Santuário da Penha',           image_class: 'image-santuario-penha',   badge: null, link: 'https://pt.wikipedia.org/wiki/Santu%C3%A1rio_da_Penha', description: 'Imponente santuário em granito no alto da Penha, lugar de peregrinação com vistas magníficas sobre a cidade.' },
  { category: 'Monumentos',       title: 'Padrão do Salado',             image_class: 'image-padrao-salado',     badge: null, link: 'https://blog.araduca.pt/search/label/Monumentos', description: 'Monumento gótico do século XIV no Largo da Oliveira, que comemora a vitória cristã na Batalha do Salado.' },
  { category: 'Praças',           title: 'Campo da Feira',               image_class: 'image-campo-feira',       badge: null, link: 'https://blog.araduca.pt/2016/05/guimaraes-e-o-seu-campo-da-feira-em-1864.html?m=1', description: 'Hoje Largo República do Brasil, o antigo campo de feiras da cidade encanta com os seus jardins floridos e a vista para a Igreja dos Santos Passos.' },
  { category: 'Praças',           title: 'Largo da Oliveira',            image_class: 'image-largo-oliveira',    badge: null, link: 'https://www.visitguimaraes.travel/descobrir-guimaraes/centro-urbano/centro-historico-patrimonio-mundial/conheca-o-centro-historico-de-guimaraes/geo_artigo/largo-da-oliveira', description: 'O coração pulsante de Guimarães: esplanadas, o Padrão do Salado e a fachada da Igreja da Oliveira criam um cenário medieval único.' },
  { category: 'Praças',           title: 'Praça de Santiago',            image_class: 'image-praca-santiago',    badge: null, link: 'https://www.visitguimaraes.travel/descobrir-guimaraes/centro-urbano/centro-historico-patrimonio-mundial/conheca-o-centro-historico-de-guimaraes', description: 'Rodeada de casas medievais, esta praça animada é o centro da vida noturna e gastronómica do centro histórico de Guimarães.' }
];

// Mapa: classe de imagem usada na BD -> ficheiro local em img_pontos/
const PLACE_IMAGES = {
  'image-paco-duques':      'img_pontos/pacos_duques.jpg',
  'image-castelo-guimaraes':'img_pontos/castelo_guimaraes.jpg',
  'image-centro-historico': 'img_pontos/centro_historico.jpg',
  'image-igreja-oliveira':  'img_pontos/igreja.jpg',
  'image-museu-martins':    'img_pontos/museu.jpg',
  'image-serra-penha':      'img_pontos/serra_penha.jpg',
  'image-museu-alberto':    'img_pontos/museu_alberto.jpg',
  'image-ciajg':            'img_pontos/ciajg.jpg',
  'image-muralhas':         'img_pontos/muralhas.jpg',
  'image-santuario-penha':  'img_pontos/santuario_penha.jpg',
  'image-padrao-salado':    'img_pontos/padrao_salado.jpg',
  'image-campo-feira':      'img_pontos/campo_feira.jpg',
  'image-largo-oliveira':   'images/web/largo-da-oliveira.jpg',
  'image-praca-santiago':   'images/web/praca-santiago.jpg'
};

let allPlaces = [];          // últimos resultados recebidos (API ou fallback)
let showAllPOI = false;      // false = mostra 6; true = mostra todos

// Constrói o cartão HTML de um ponto de interesse (mesmo formato dos estáticos)
function buildPlaceCard(place, idx) {
  const img = PLACE_IMAGES[place.image_class] || 'images/web/centro-historico.jpg';
  const isFirst = idx === 0 && !showAllPOI;
  const card = document.createElement('div');
  card.className = 'card fade-in' + (isFirst ? ' card-large' : '');
  card.innerHTML = `
    <div class="card-img-wrap">
      <img src="${img}" alt="${place.title}" loading="${isFirst ? 'eager' : 'lazy'}" />
      ${place.badge ? `<span class="card-badge${place.badge === 'UNESCO' ? ' card-badge-alt' : ''}">${place.badge}</span>` : ''}
    </div>
    <div class="card-body">
      <span class="card-cat">${place.category || 'Local'}</span>
      <h3>${place.title || ''}</h3>
      <p class="card-desc">${place.description || ''}</p>
      <a href="${place.link || '#'}" class="card-link" target="_blank" rel="noopener">${L('readMore')} <span>→</span></a>
    </div>`;
  // Anima os cartões dinâmicos com o mesmo observer dos estáticos
  setTimeout(() => card.classList.add('visible'), idx * 60);
  return card;
}

// Desenha os cartões na grelha (6 iniciais ou todos)
function renderPlaces(places) {
  const grid = document.getElementById('tourismResults');
  if (!grid) return;
  grid.innerHTML = '';
  if (!places.length) { grid.hidden = false; return; }
  (showAllPOI ? places : places.slice(0, 5)).forEach((p, i) => grid.appendChild(buildPlaceCard(p, i)));
  grid.hidden = false;
}

// Consulta a API de pontos de interesse; usa a lista local se estiver offline
async function fetchPlaces(query) {
  const status = document.getElementById('tourismStatus');
  const grid   = document.getElementById('tourismResults');

  try {
    const url = new URL(API.places);
    if (query) url.searchParams.set('q', query);
    url.searchParams.set('lang', currentLang);
    const r = await fetch(url);
    if (!r.ok) throw new Error('API ' + r.status);
    const data = await r.json();
    allPlaces = data.results || [];
    if (status) status.textContent = allPlaces.length ? '' : L('noResults');
  } catch (_) {
    // Offline: filtra a lista local (no idioma atual) com o mesmo critério da API.
    // A normalização remove acentos: "paco" também encontra "Paço"
    const norm = (s) => s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
    const base = currentLang === 'en' ? FALLBACK_PLACES_EN : FALLBACK_PLACES;
    const q = norm(query || '');
    allPlaces = q
      ? base.filter(p => norm(p.title + p.description + p.category).includes(q))
      : base;
    if (status) status.textContent = allPlaces.length ? L('apiOffline') : L('noResults');
  }
  renderPlaces(allPlaces);
}

// Meses aceites no cartão de evento (abreviaturas PT e EN) -> número do mês
const MESES_EVENTO = { jan:1, fev:2, feb:2, mar:3, abr:4, apr:4, mai:5, may:5, jun:6, jul:7, ago:8, aug:8, set:9, sep:9, out:10, oct:10, nov:11, dez:12, dec:12 };

// Procura eventos no dia escolhido (campo "Quando?"), destaca os cartões
// correspondentes e escreve o resultado por baixo da lista de eventos
function destacaEventosNaData(dataISO) {
  const [, mes, dia] = dataISO.split('-').map(Number);
  const status = document.getElementById('eventsStatus');
  const encontrados = [];
  document.querySelectorAll('.event-card').forEach(card => {
    card.classList.remove('event-highlight');
    const d = parseInt(card.querySelector('.event-day')?.textContent, 10);
    const m = MESES_EVENTO[card.querySelector('.event-month')?.textContent.trim().toLowerCase()] || 0;
    if (d === dia && m === mes) {
      card.classList.add('event-highlight');
      encontrados.push(card.querySelector('h4')?.textContent);
    }
  });
  if (status) {
    status.textContent = encontrados.length
      ? `📅 ${L('eventFound')} ${String(dia).padStart(2, '0')}/${String(mes).padStart(2, '0')}: ${encontrados.join(' · ')}`
      : L('eventNone');
  }
  return encontrados.length > 0;
}

// Pesquisa nas ligações externas: destaca as que correspondem ao termo
// (insensível a acentos) e esbate as restantes; mostra a contagem
function filtraLigacoes(query) {
  const norm = (s) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
  const cards = [...document.querySelectorAll('.ligacao-card')];
  const status = document.getElementById('ligacoesStatus');
  const q = norm(query);

  if (!q) {
    cards.forEach(c => c.classList.remove('ligacao-match', 'ligacao-dim'));
    if (status) status.textContent = '';
    return 0;
  }

  let encontrados = 0;
  cards.forEach(c => {
    const texto = norm(c.textContent + ' ' + (c.getAttribute('href') || ''));
    const match = texto.includes(q);
    c.classList.toggle('ligacao-match', match);
    c.classList.toggle('ligacao-dim', !match);
    if (match) encontrados++;
  });

  if (status) {
    status.textContent = encontrados
      ? `🔗 ${encontrados} ${L('linksFound')} "${query}"`
      : `${L('linksNone')} "${query}".`;
  }
  return encontrados;
}

// Pesquisa inteligente ("modo IA"): envia a consulta ao Gemini (POST /api/search)
// e mostra uma síntese no painel; se a IA falhar, esconde o painel sem incomodar
async function searchAI(query) {
  const painel = document.getElementById('aiAnswer');
  const corpo  = document.getElementById('aiAnswerBody');
  const label  = document.getElementById('aiAnswerLabel');
  const nota   = document.getElementById('aiAnswerNote');
  if (!painel) return;

  // Mostra o painel com o indicador "a escrever" (três pontos animados)
  label.textContent = L('aiLabel');
  nota.textContent = '';
  corpo.classList.add('ai-loading');
  corpo.innerHTML = '<span></span><span></span><span></span>';
  painel.hidden = false;

  try {
    const r = await fetch(API.search, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, lang: currentLang })
    });
    const data = await r.json();
    corpo.classList.remove('ai-loading');
    if (data.ok && data.answer) {
      corpo.textContent = data.answer;
      nota.textContent = L('aiNote');
    } else {
      corpo.textContent = L('aiOffline');
    }
  } catch (_) {
    // IA offline — esconde o painel para não atrapalhar os resultados locais
    corpo.classList.remove('ai-loading');
    painel.hidden = true;
  }
}

// ══════════════════════════════════════════════════════════════
//  PESQUISA INTERATIVA COM IA — hero search panel + typewriter
// ══════════════════════════════════════════════════════════════

const HS_SUGGESTIONS = [
  { group:'Monumentos', icon:'🏰', title:'Castelo de Guimarães', sub:'Símbolo da fundação de Portugal', q:'Castelo de Guimarães', anchor:'descobrir' },
  { group:'Monumentos', icon:'🏛️', title:'Paço dos Duques de Bragança', sub:'Palácio gótico do séc. XV', q:'Paço dos Duques', anchor:'descobrir' },
  { group:'Monumentos', icon:'🏺', title:'Museu Alberto Sampaio', sub:'Arte sacra e medieval', q:'Museu Alberto Sampaio', anchor:'descobrir' },
  { group:'Monumentos', icon:'⛪', title:'Igreja da Oliveira', sub:'No coração do centro histórico', q:'Igreja Oliveira', anchor:'descobrir' },
  { group:'Atividades', icon:'🚠', title:'Teleférico da Penha', sub:'Vistas deslumbrantes sobre a cidade', q:'Teleférico da Penha', anchor:'atividades' },
  { group:'Atividades', icon:'🥾', title:'Trilhos na Natureza', sub:'Serra da Penha e parques naturais', q:'Trilhos natureza Guimarães', anchor:'atividades' },
  { group:'Atividades', icon:'⚽', title:'Vitória SC — Estádio', sub:'Futebol em Guimarães', q:'Vitória Sport Clube estádio', anchor:'atividades' },
  { group:'Gastronomia', icon:'🍰', title:'Pão-de-Ló de Margaride', sub:'Doce conventual típico', q:'Pão-de-Ló Guimarães', anchor:'gastronomia' },
  { group:'Gastronomia', icon:'🐟', title:'Bacalhau à Minhota', sub:'Prato tradicional do norte', q:'Gastronomia típica Guimarães', anchor:'gastronomia' },
  { group:'Gastronomia', icon:'🍷', title:'Vinho Verde', sub:'Vinhos frescos da região do Minho', q:'Vinho verde Guimarães', anchor:'gastronomia' },
  { group:'Alojamento', icon:'🏨', title:'Hotéis no centro histórico', sub:'Perto dos monumentos', q:'Hotéis centro histórico Guimarães', anchor:'alojamento' },
  { group:'Eventos', icon:'📅', title:'Agenda cultural', sub:'Festividades e eventos locais', q:'Eventos e festividades Guimarães', anchor:'eventos' },
];

function _norm(s) {
  return (s||'').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'');
}

function hsRenderPanel(query) {
  const panel = document.getElementById('hsPanel');
  const body  = document.getElementById('hsPanelBody');
  if (!panel || !body) return;

  const q = _norm(query);
  const filtered = q
    ? HS_SUGGESTIONS.filter(it => _norm(it.title+' '+it.sub+' '+it.group+' '+it.q).includes(q))
    : HS_SUGGESTIONS;

  if (!filtered.length) {
    body.innerHTML = `<div class="hs-no-results">Sem sugestões para "<strong>${query}</strong>" — prima Enter para pesquisar com IA</div>`;
    panel.hidden = false; return;
  }

  const groups = {};
  for (const it of filtered) { (groups[it.group] = groups[it.group]||[]).push(it); }

  let html = '';
  const entries = Object.entries(groups);
  entries.forEach(([grp, items], gi) => {
    html += `<div class="hs-group-label">${grp}</div>`;
    items.forEach(it => {
      html += `<div class="hs-item" data-q="${it.q}" data-anchor="${it.anchor}">
        <div class="hs-item-icon">${it.icon}</div>
        <div class="hs-item-text">
          <div class="hs-item-title">${it.title}</div>
          <div class="hs-item-sub">${it.sub}</div>
        </div>
        <span class="hs-item-arr">→</span>
      </div>`;
    });
    if (gi < entries.length - 1) html += '<div class="hs-sep"></div>';
  });
  body.innerHTML = html;

  body.querySelectorAll('.hs-item').forEach(el => {
    el.addEventListener('click', () => {
      const q2 = el.dataset.q;
      document.getElementById('tourismQuery').value = q2;
      panel.hidden = true;
      hsSearch(q2);
    });
  });

  panel.hidden = false;
}

function hsClosePanel() {
  const p = document.getElementById('hsPanel');
  if (p) p.hidden = true;
}

// Typewriter effect
function hsTypewriter(el, text, speed = 18) {
  el.classList.add('hs-ai-cursor');
  let i = 0;
  el.textContent = '';
  const tick = () => {
    if (i < text.length) {
      el.textContent += text[i++];
      setTimeout(tick, speed);
    } else {
      el.classList.remove('hs-ai-cursor');
    }
  };
  tick();
}

// Quick-action chips baseados na resposta IA
function hsActionChips(query) {
  const q = query.toLowerCase();
  const chips = [];
  if (/castelo|palácio|paço|muralha|monumentos/.test(q)) chips.push({ label:'📍 Ver no mapa', anchor:'transportes' });
  if (/gastronomia|restaurante|comer|vinho|pão|bacalhau/.test(q)) chips.push({ label:'🍽️ Ver gastronomia', anchor:'gastronomia' });
  if (/hotel|pousada|alojamento|dormir|ficar/.test(q)) chips.push({ label:'🏨 Ver alojamento', anchor:'alojamento' });
  if (/evento|festival|agenda|quando/.test(q)) chips.push({ label:'📅 Ver eventos', anchor:'eventos' });
  if (/atividade|trilho|teleférico|desporto/.test(q)) chips.push({ label:'🎯 Ver atividades', anchor:'atividades' });
  chips.push({ label:'🗺️ Descobrir mais', anchor:'descobrir' });
  return chips.slice(0, 3);
}

async function hsSearch(query) {
  if (!query) return;
  const aiBox    = document.getElementById('hsAi');
  const aiBody   = document.getElementById('hsAiBody');
  const aiActions= document.getElementById('hsAiActions');
  if (!aiBox || !aiBody) return;

  hsClosePanel();

  // Mostrar loading
  aiBox.hidden = false;
  aiBody.innerHTML = '<div class="hs-ai-loading"><div class="hs-dot"></div><div class="hs-dot"></div><div class="hs-dot"></div></div>';
  aiActions.innerHTML = '';

  // Filtrar cards + ligações em paralelo
  showAllPOI = true;
  fetchPlaces(query);
  filtraLigacoes(query);

  // Chamar API IA
  try {
    const r = await fetch(API.search, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, lang: currentLang })
    });
    const data = await r.json();
    if (data.ok && data.answer) {
      aiBody.innerHTML = '';
      hsTypewriter(aiBody, data.answer);
    } else {
      aiBody.textContent = L('aiOffline');
    }
  } catch (_) {
    aiBody.textContent = 'Sem ligação ao servidor IA. Os resultados abaixo foram filtrados localmente.';
  }

  // Chips de ação
  const chips = hsActionChips(query);
  aiActions.innerHTML = chips.map(c =>
    `<button class="hs-ai-action" data-anchor="${c.anchor}">${c.label}</button>`
  ).join('');
  aiActions.querySelectorAll('.hs-ai-action').forEach(btn => {
    btn.addEventListener('click', () => {
      document.getElementById(btn.dataset.anchor)?.scrollIntoView({ behavior:'smooth' });
    });
  });

  // Scroll suave para a secção de resultados
  setTimeout(() => {
    document.getElementById('descobrir')?.scrollIntoView({ behavior:'smooth', block:'start' });
  }, 400);
}

// Fechar resposta IA
document.getElementById('hsAiClose')?.addEventListener('click', () => {
  document.getElementById('hsAi').hidden = true;
});

// Abrir painel ao focar o campo
document.getElementById('tourismQuery')?.addEventListener('focus', function() {
  hsRenderPanel(this.value.trim());
});

// Filtrar ao escrever
document.getElementById('tourismQuery')?.addEventListener('input', function() {
  hsRenderPanel(this.value.trim());
  if (!this.value.trim()) {
    const ai = document.getElementById('hsAi');
    if (ai) ai.hidden = true;
  }
});

// Fechar painel ao clicar fora
document.addEventListener('click', e => {
  const hero = document.getElementById('heroSearch');
  if (hero && !hero.contains(e.target)) hsClosePanel();
});

// Fechar com Escape
document.getElementById('tourismQuery')?.addEventListener('keydown', e => {
  if (e.key === 'Escape') { hsClosePanel(); document.getElementById('tourismQuery').blur(); }
});

// Submit do formulário
document.getElementById('tourismSearchForm')?.addEventListener('submit', (e) => {
  e.preventDefault();
  const query = document.getElementById('tourismQuery').value.trim();
  const data  = document.getElementById('tourismDate')?.value || '';
  hsClosePanel();
  if (query) {
    hsSearch(query);
  } else {
    const ai = document.getElementById('hsAi');
    if (ai) ai.hidden = true;
    fetchPlaces('');
    filtraLigacoes('');
    const painel = document.getElementById('aiAnswer');
    if (painel) painel.hidden = true;
  }
  if (data) destacaEventosNaData(data);
  if (!query && data) document.getElementById('eventos')?.scrollIntoView({ behavior:'smooth' });
});

// Configuração do campo de data: não permite escolher dias no passado
const campoData = document.getElementById('tourismDate');
if (campoData) campoData.min = new Date().toISOString().slice(0, 10);

// Botão "Ver todos os pontos de interesse" — alterna 6/todos
document.getElementById('showAllPlaces')?.addEventListener('click', (e) => {
  e.preventDefault();
  showAllPOI = !showAllPOI;
  renderPlaces(allPlaces.length ? allPlaces : (currentLang === 'en' ? FALLBACK_PLACES_EN : FALLBACK_PLACES));
  e.target.textContent = showAllPOI ? L('showLess') : L('showAll');
});

// ── LIGHTBOX DA GALERIA ──────────────────────────────────────────────────────
const lbEl      = document.getElementById('lightbox');
const lbImg     = document.getElementById('lbImg');
const lbCaption = document.getElementById('lbCaption');
const lbCounter = document.getElementById('lbCounter');

const galeriaItems = [...document.querySelectorAll('.galeria-item')];
let lbIndex = 0;

function lbOpen(idx) {
  lbIndex = idx;
  const item = galeriaItems[idx];
  const img  = item.querySelector('img');
  const cap  = item.querySelector('.galeria-caption');
  lbImg.src = img.src;
  lbImg.alt = img.alt;
  lbCaption.textContent = cap ? cap.textContent : img.alt;
  lbCounter.textContent = `${idx + 1} / ${galeriaItems.length}`;
  lbEl.hidden = false;
  document.body.style.overflow = 'hidden';
}

function lbClose() {
  lbEl.hidden = true;
  lbImg.src = '';
  document.body.style.overflow = '';
}

function lbGo(dir) {
  lbIndex = (lbIndex + dir + galeriaItems.length) % galeriaItems.length;
  lbOpen(lbIndex);
}

galeriaItems.forEach((item, i) => item.addEventListener('click', () => lbOpen(i)));
document.getElementById('lbClose')?.addEventListener('click', lbClose);
document.getElementById('lbPrev')?.addEventListener('click', () => lbGo(-1));
document.getElementById('lbNext')?.addEventListener('click', () => lbGo(+1));

lbEl?.addEventListener('click', e => { if (e.target === lbEl) lbClose(); });

document.addEventListener('keydown', e => {
  if (lbEl?.hidden) return;
  if (e.key === 'Escape')     lbClose();
  if (e.key === 'ArrowLeft')  lbGo(-1);
  if (e.key === 'ArrowRight') lbGo(+1);
});

// Carrega os pontos de interesse ao abrir a página
fetchPlaces('');

/* ============================================================
   CHATBOT IA — janela flutuante ligada ao backend
   (POST /api/chat -> Google Gemini; respostas locais se offline)
   ============================================================ */

const chatToggle = document.getElementById('chatToggle');
const chatBox = document.getElementById('chatBox');
const chatMessages = document.getElementById('chatMessages');
const chatInput = document.getElementById('chatInput');

// Histórico da conversa (memória), persistido no localStorage entre visitas
let chatHistory = JSON.parse(localStorage.getItem('chatHistory') || '[]');
const guardaHistorico = () => localStorage.setItem('chatHistory', JSON.stringify(chatHistory.slice(-20)));

// Abre/fecha a janela de chat
chatToggle?.addEventListener('click', () => {
  chatBox.style.display = chatBox.style.display === 'flex' ? 'none' : 'flex';
  if (chatBox.style.display === 'flex') chatInput?.focus();
});
document.getElementById('closeChat')?.addEventListener('click', () => { chatBox.style.display = 'none'; });

// Limpar conversa: apaga o histórico e volta à saudação inicial
document.getElementById('clearChat')?.addEventListener('click', () => {
  chatHistory = [];
  guardaHistorico();
  chatMessages.querySelectorAll('.chat-msg').forEach(el => el.remove());
  renderDefaultSuggestions();
  chatInput?.focus();
});

// Adiciona um balão de mensagem (utilizador ou bot) à conversa.
// registar=true grava no histórico (não se faz ao restaurar do localStorage)
function addChatBubble(texto, deUtilizador, registar = true) {
  const b = document.createElement('div');
  b.className = 'chat-msg';
  b.style.cssText = 'padding:10px;border-radius:8px;max-width:80%;font-size:14px;white-space:pre-wrap;' +
    (deUtilizador ? 'background:#b57c3d;color:white;align-self:flex-end;' : 'background:#e9e9e9;color:black;align-self:flex-start;');
  b.textContent = texto;
  chatMessages.appendChild(b);
  chatMessages.scrollTop = chatMessages.scrollHeight;
  if (registar) {
    chatHistory.push({ role: deUtilizador ? 'user' : 'bot', text: texto });
    guardaHistorico();
  }
  return b;
}

// Resposta local quando a API de IA não está disponível.
// Procura palavras-chave na pergunta e responde no idioma atual.
function localBotReply(p) {
  const t = p.toLowerCase();
  const respostas = {
    pt: [
      [/castelo/, 'O Castelo de Guimarães, do século X, é considerado o berço de Portugal — fica no alto da colina, junto ao Paço dos Duques. Entrada gratuita ao domingo de manhã para residentes.'],
      [/pa[çc]o|duques/, 'O Paço dos Duques de Bragança é um palácio do século XV, hoje residência oficial do Presidente da República no Norte. Pode visitá-lo todos os dias — veja pacodosduques.gov.pt.'],
      [/visitar|monumento|ver|conhecer|pontos/, 'Os imperdíveis: Castelo de Guimarães, Paço dos Duques, Centro Histórico (UNESCO), Igreja da Oliveira, Santuário da Penha e o Museu Alberto Sampaio. Veja a secção "Descobrir" da página!'],
      [/comer|restaurante|gastronomia|prato|comida/, 'Experimente o bacalhau à vimaranense, o pão-de-ló de Margaride e o vinho verde da região. No Largo da Oliveira e na Praça de Santiago há boas tascas e esplanadas.'],
      [/dormir|hotel|alojamento|ficar|pousada/, 'Veja a secção Alojamento: Hotel da Oliveira (no centro histórico), Pousada Mosteiro de Guimarães (na encosta da Penha) ou a Pousada de Juventude para orçamentos mais apertados.'],
      [/penha|telef[ée]rico|subir/, 'Suba à Penha de teleférico (turipenha.pt) ou a pé — a vista sobre Guimarães vale a viagem. Lá em cima encontra o Santuário da Penha, miradouros e parque de merendas.'],
      [/evento|festa|agenda|concerto/, 'Destaques do ano: Festas Gualterianas (junho), GNRation Festival (julho), Feira Medieval (agosto) e Meia Maratona (setembro). Agenda completa em em.guimaraes.pt.'],
      [/hist[óo]ria|nasceu|fundação|afonso/, 'Guimarães é o berço de Portugal: D. Afonso Henriques venceu aqui a Batalha de São Mamede em 1128. O Centro Histórico é Património Mundial da UNESCO desde 2001.'],
      [/chegar|comboio|carro|avi[ãa]o|transporte/, 'De comboio: linha do Minho com estação no centro. De carro: A3 + A11 ou A7. De avião: aeroporto do Porto a 50 km. Veja o mapa no fim da página.'],
      [/museu/, 'Não perca o Museu Martins Sarmento (arqueologia castreja), o Museu Alberto Sampaio (arte sacra) e o CIAJG na Plataforma das Artes (arte contemporânea).']
    ],
    en: [
      [/castle/, 'Guimarães Castle, from the 10th century, is considered the birthplace of Portugal — it sits on the hilltop next to the Palace of the Dukes.'],
      [/palace|dukes/, 'The Palace of the Dukes of Braganza is a 15th-century palace, today an official residence of the Portuguese President. Open daily — see pacodosduques.gov.pt.'],
      [/visit|monument|see|sights|places/, 'The must-sees: Guimarães Castle, Palace of the Dukes, the UNESCO Historic Centre, Oliveira Church, Penha Sanctuary and the Alberto Sampaio Museum. Check the "Discover" section!'],
      [/eat|restaurant|food|gastronomy|dish/, 'Try the bacalhau à vimaranense, the pão-de-ló from Margaride and the local vinho verde. Largo da Oliveira and Santiago Square have great taverns and terraces.'],
      [/sleep|hotel|stay|accommodation/, 'See the Accommodation section: Hotel da Oliveira (historic centre), the Pousada in the old monastery on Penha hill, or the Youth Hostel for tighter budgets.'],
      [/penha|cable/, 'Go up Penha by cable car (turipenha.pt) or on foot — the view over Guimarães is worth it. At the top you will find the Penha Sanctuary and several viewpoints.'],
      [/event|festival|agenda|concert/, 'Highlights: Gualterianas Festivities (June), GNRation Festival (July), Medieval Fair (August) and the Half Marathon (September). Full agenda at em.guimaraes.pt.'],
      [/history|born|founded|afonso/, 'Guimarães is the birthplace of Portugal: Afonso Henriques won the Battle of São Mamede here in 1128. The Historic Centre has been a UNESCO World Heritage site since 2001.'],
      [/train|car|plane|transport|get to|arrive/, 'By train: Minho line with a station in the centre. By car: A3 + A11 or A7. By plane: Porto airport, 50 km away. See the map at the bottom of the page.'],
      [/museum/, 'Do not miss the Martins Sarmento Museum (archaeology), the Alberto Sampaio Museum (sacred art) and the CIAJG at the Platform of Arts (contemporary art).']
    ]
  };
  for (const [padrao, resposta] of respostas[currentLang]) {
    if (padrao.test(t)) return resposta;
  }
  return L('chatFallback');
}

// Remove marcas Markdown simples (**negrito**, *itálico*, ### títulos)
// que o modelo de IA por vezes devolve, para os balões ficarem limpos
function limpaMarkdown(texto) {
  return texto
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/^#{1,4}\s*/gm, '')
    .trim();
}

// Sugestões: conjunto inicial + seguimentos contextuais por tema (PT/EN)
const CHAT_SUGGESTIONS = {
  pt: {
    default: ['O que visitar em Guimarães?', 'Onde comer pratos típicos?', 'Como subir à Penha?', 'Onde ficar alojado?'],
    follow: [
      [/castelo|pa[çc]o|duques|monumento|visitar|centro|igreja/, ['Qual o horário do castelo?', 'Quanto custa a entrada?', 'Como chego ao centro histórico?']],
      [/comer|restaurante|gastronom|prato|bacalhau|p[ãa]o|vinho|doce/, ['Onde provar o pão-de-ló?', 'Quanto custa uma refeição típica?', 'Há esplanadas no centro?']],
      [/penha|telef|trilho|natureza|subir/, ['Quanto custa o teleférico?', 'Qual o horário do teleférico?', 'Dá para subir a pé?']],
      [/dormir|hotel|aloj|ficar|pousada/, ['Qual a melhor zona para ficar?', 'Há hostels mais baratos?', 'Fica perto do centro?']],
      [/evento|festa|agenda|concerto|feira|gualteriana/, ['Que eventos há este mês?', 'Quando são as Gualterianas?', 'A Feira Medieval é quando?']],
      [/chegar|comboio|carro|avi[ãa]o|transporte|estacion/, ['Quanto demora desde o Porto?', 'Há estacionamento no centro?', 'Onde fica a estação?']]
    ]
  },
  en: {
    default: ['What to visit in Guimarães?', 'Where to eat local dishes?', 'How to go up to Penha?', 'Where to stay?'],
    follow: [
      [/castle|palace|dukes|monument|visit|centre|center|church/, ['What are the castle hours?', 'How much is admission?', 'How do I reach the historic centre?']],
      [/eat|restaurant|food|dish|codfish|cake|wine/, ['Where to try the pão-de-ló?', 'How much is a typical meal?', 'Are there terraces downtown?']],
      [/penha|cable|trail|nature|hike/, ['How much is the cable car?', 'What are the cable car hours?', 'Can I walk up?']],
      [/sleep|hotel|stay|accommodation/, ['Which area is best to stay?', 'Are there cheaper hostels?', 'Is it near the centre?']],
      [/event|festival|agenda|concert|fair/, ['What events are on this month?', 'When are the Gualterianas?', 'When is the Medieval Fair?']],
      [/arrive|train|car|plane|transport|parking|get to/, ['How long from Porto?', 'Is there parking downtown?', 'Where is the station?']]
    ]
  }
};

// Reconstrói os botões de sugestão; cada clique envia a pergunta ao Guigas
function renderSuggestions(lista) {
  const cx = document.getElementById('chatSuggestions');
  if (!cx) return;
  cx.innerHTML = '';
  lista.forEach(texto => {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'chat-suggestion';
    b.textContent = texto;
    b.addEventListener('click', () => {
      if (chatBox.style.display !== 'flex') chatBox.style.display = 'flex';
      sendChat(texto);
    });
    cx.appendChild(b);
  });
}
const renderDefaultSuggestions = () => renderSuggestions(CHAT_SUGGESTIONS[currentLang].default);

// Escolhe seguimentos relevantes com base no tema da conversa
function escolheFollowups(texto) {
  const t = (texto || '').toLowerCase();
  for (const [padrao, lista] of CHAT_SUGGESTIONS[currentLang].follow) {
    if (padrao.test(t)) return lista;
  }
  return CHAT_SUGGESTIONS[currentLang].default;
}

// Evita envios duplicados enquanto uma resposta está a caminho
let chatOcupado = false;

// Envia a pergunta ao backend (com o histórico recente como contexto)
// e mostra a resposta; depois sugere perguntas de seguimento
async function sendChat(textoForcado) {
  const pergunta = (textoForcado || chatInput.value || '').trim();
  if (!pergunta || chatOcupado) return;
  chatOcupado = true;
  const btn = document.getElementById('chatSendBtn');
  if (btn) btn.disabled = true;
  chatInput.value = '';

  const historicoEnviar = chatHistory.slice(-8); // contexto antes desta pergunta
  addChatBubble(pergunta, true);

  // Indicador "a escrever" com três pontos animados (não entra no histórico)
  const espera = addChatBubble('', false, false);
  espera.classList.add('chat-typing');
  espera.setAttribute('aria-label', L('thinking'));
  espera.innerHTML = '<span></span><span></span><span></span>';

  let resposta;
  try {
    const r = await fetch(API.chat, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: pergunta, lang: currentLang, history: historicoEnviar })
    });
    const data = await r.json();
    resposta = (data.ok && data.reply) ? limpaMarkdown(data.reply) : localBotReply(pergunta);
  } catch (_) {
    resposta = localBotReply(pergunta);
  } finally {
    espera.classList.remove('chat-typing');
    espera.removeAttribute('aria-label');
    espera.textContent = resposta;
    chatHistory.push({ role: 'bot', text: resposta });
    guardaHistorico();
    chatOcupado = false;
    if (btn) btn.disabled = false;
    chatInput.focus();
    chatMessages.scrollTop = chatMessages.scrollHeight;
    // Sugestões de seguimento relacionadas com o que foi perguntado
    renderSuggestions(escolheFollowups(pergunta));
  }
}

document.getElementById('chatSendBtn')?.addEventListener('click', () => sendChat());
chatInput?.addEventListener('keypress', (e) => { if (e.key === 'Enter') sendChat(); });

// Restaura a conversa anterior (guardada no localStorage) ao abrir a página
function restoreChat() {
  if (!chatMessages || !chatHistory.length) return;
  chatHistory.forEach(m => addChatBubble(m.text, m.role === 'user', false));
}
restoreChat();
renderDefaultSuggestions();

// Tecla Escape fecha a janela de chat
document.addEventListener('keydown', (e) => {
  if (e.key === 'Escape' && chatBox.style.display === 'flex') chatBox.style.display = 'none';
});

/* ============================================================
   INTERNACIONALIZAÇÃO PT | EN
   O HTML está escrito em português (idioma original). Ao mudar
   para inglês, os textos são substituídos pelo dicionário EN;
   os textos PT originais são guardados em cache para repor.
   ============================================================ */

// Lista local EN (fallback dos pontos de interesse quando a API está offline)
const FALLBACK_PLACES_EN = [
  { category: 'Palaces',         title: 'Palace of the Dukes of Braganza', image_class: 'image-paco-duques',      badge: 'Must-see', link: 'https://pacodosduques.gov.pt/', description: "Built in the 15th century by the 1st Duke of Braganza, it is one of Portugal's most striking medieval palaces." },
  { category: 'Monuments',       title: 'Guimarães Castle',                image_class: 'image-castelo-guimaraes', badge: null, link: 'https://pacodosduques.gov.pt/monumentos/castelo-de-guimaraes/', description: "A symbol of Portugal's foundation and one of the city's most iconic monuments." },
  { category: 'Historic Centre', title: 'Historic Centre',                 image_class: 'image-centro-historico',  badge: 'UNESCO', link: 'https://unescoportugal.mne.gov.pt/pt/temas/proteger-o-nosso-patrimonio-e-promover-a-criatividade/patrimonio-mundial-em-portugal/centro-historico-de-guimaraes', description: 'Medieval streets, lively squares and a unique atmosphere that invites you to explore on foot.' },
  { category: 'Churches',        title: 'Oliveira Church',                 image_class: 'image-igreja-oliveira',   badge: null, link: 'https://pt.wikipedia.org/wiki/Categoria:Igrejas_em_Guimar%C3%A3es', description: 'One of the most important religious and historical landmarks in the heart of the city.' },
  { category: 'Museums',         title: 'Martins Sarmento Museum',         image_class: 'image-museu-martins',     badge: null, link: 'https://www.museusemonumentos.pt/pt/museus-e-monumentos', description: "A landmark archaeological collection to better understand the region's Celtic and Roman heritage." },
  { category: 'Nature',          title: 'Penha Mountain',                  image_class: 'image-serra-penha',       badge: null, link: 'https://www.penhaguimaraes.com/pt/', description: 'Go up by cable car or on foot and enjoy one of the best panoramic views over Guimarães.' },
  { category: 'Museums',         title: 'Alberto Sampaio Museum',          image_class: 'image-museu-alberto',     badge: null, link: 'https://www.museusemonumentos.pt/pt/museus-e-monumentos', description: 'Housed in the former collegiate convent, it holds outstanding medieval goldwork, sculpture and textiles.' },
  { category: 'Museums',         title: 'José de Guimarães International Arts Centre', image_class: 'image-ciajg', badge: null, link: 'https://www.ciajg.pt/sobre/', description: 'Opened in 2012 at the Platform of Arts and Creativity, it is devoted to contemporary art and the collection of the artist José de Guimarães.' },
  { category: 'Monuments',       title: 'Medieval Walls',                  image_class: 'image-muralhas',          badge: null, link: 'http://www.monumentos.gov.pt/site/app_pagesuser/SIPA.aspx?id=1048', description: 'Remaining sections of the walls that once enclosed the medieval city, silent witnesses to centuries of history.' },
  { category: 'Churches',        title: 'Penha Sanctuary',                 image_class: 'image-santuario-penha',   badge: null, link: 'https://pt.wikipedia.org/wiki/Santu%C3%A1rio_da_Penha', description: 'An imposing granite sanctuary at the top of Penha hill, a pilgrimage site with magnificent views over the city.' },
  { category: 'Monuments',       title: 'Salado Monument',                 image_class: 'image-padrao-salado',     badge: null, link: 'https://blog.araduca.pt/search/label/Monumentos', description: 'A 14th-century Gothic monument in Largo da Oliveira commemorating the Christian victory at the Battle of Salado.' },
  { category: 'Squares',         title: 'Campo da Feira',                  image_class: 'image-campo-feira',       badge: null, link: 'https://blog.araduca.pt/2016/05/guimaraes-e-o-seu-campo-da-feira-em-1864.html?m=1', description: "Now Largo República do Brasil, the city's old fairground charms visitors with flower-filled gardens and views of the Santos Passos Church." },
  { category: 'Squares',         title: 'Largo da Oliveira',               image_class: 'image-largo-oliveira',    badge: null, link: 'https://www.visitguimaraes.travel/descobrir-guimaraes/centro-urbano/centro-historico-patrimonio-mundial/conheca-o-centro-historico-de-guimaraes/geo_artigo/largo-da-oliveira', description: 'The beating heart of Guimarães: terraces, the Salado Monument and the façade of Oliveira Church create a unique medieval setting.' },
  { category: 'Squares',         title: 'Santiago Square',                 image_class: 'image-praca-santiago',    badge: null, link: 'https://www.visitguimaraes.travel/descobrir-guimaraes/centro-urbano/centro-historico-patrimonio-mundial/conheca-o-centro-historico-de-guimaraes', description: "Surrounded by medieval houses, this lively square is the hub of nightlife and gastronomy in Guimarães's historic centre." }
];

// Dicionário EN — textos simples (textContent), por seletor CSS.
// Um array aplica-se aos elementos pela ordem em que aparecem na página.
const EN_TEXTS = {
  '.nav-links li a': ['Discover', 'History', 'Activities', 'Gastronomy', 'Gallery', 'Events', 'Accommodation', 'Links', 'Contact'],
  '.mobile-menu a': ['Discover', 'History', 'Activities', 'Gastronomy', 'Gallery', 'Events', 'Accommodation', 'Useful Links', 'Contact', 'Map'],
  '.hero-label': 'Welcome to',
  '.hero-subtitle': 'This is where Portugal was born. A city where history is not kept in a museum — it lives on the streets.',
  "label[for='tourismQuery']": 'What are you looking for?',
  "label[for='tourismDate']": 'When?',
  '.btn-search': '🔍 Search',
  '.hero-scroll span': 'Discover more',
  '.stat-label': ['Years of history', 'Residents', 'World Heritage', 'European Capital of Culture'],
  '.section-tag': ['Origins', 'Points of Interest', 'Experiences', 'Local Flavours', 'Photos', 'Agenda', 'Where to Stay', 'Useful Resources', 'Talk to Us', 'Transport'],
  '.section-title': ['History of Guimarães', 'Discover Guimarães', 'What to Do in Guimarães', 'Guimarães Gastronomy', 'Image Gallery', 'Featured Events', 'Where to Stay in Guimarães', 'External Links', 'Contact Form', 'How to Get to Guimarães'],
  '.section-desc': [
    'The city where Portugal was born, with more than a thousand years of history that helped shape a nation.',
    'There is plenty to see in Guimarães — from medieval castles to museums, churches and viewpoints with views worth keeping.',
    'Whether you want to explore the castle, go up to Penha or watch a Vitória match, there is always something to do in Guimarães.',
    'Eating well in Guimarães is easy. The local codfish, the pão-de-ló and the vinho verde speak for themselves.',
    'Some of the images that best represent Guimarães — for those who have visited and want to remember, or for those still planning the trip.',
    'From June to September the city never stops — and even off season there is always something going on.',
    'Staying in the historic centre is the best way to enjoy the city — on foot, unhurried and without missing a thing.',
    'Before you go, these websites are worth a look — timetables, tickets, transport and much more.',
    'Do you have any questions or suggestions? Send us a message and we will reply as soon as possible.'
  ],
  '.historia-ano': ['10th c.', '1128', '15th c.', '2001', '2012'],
  '.historia-item h4': ['Foundation of the County', 'Battle of São Mamede', 'Palace of the Dukes of Braganza', 'UNESCO World Heritage', 'European Capital of Culture'],
  '.historia-item p': [
    'Guimarães emerged as a centre of power in the County of Portugal, with the castle built by Mumadona Dias to defend the region from Moorish and Norman invasions.',
    'Afonso Henriques won the decisive battle near Guimarães, asserting the independence of the County of Portugal and becoming the first king of Portugal.',
    'Afonso, the 1st Duke of Braganza, commissioned the imposing Gothic palace that still dominates the castle hill and serves as an official residence of the Portuguese President.',
    "In 2001 UNESCO added the Historic Centre of Guimarães to the World Heritage List. It is one of Europe's best-preserved medieval urban ensembles.",
    'In 2012 Guimarães was European Capital of Culture. The title brought new cultural venues and put the city firmly on the European map.'
  ],
  '.activity-card h4': ['Historical Tourism', 'Penha Cable Car', 'Nature Trails', 'Art & Culture', 'Local Crafts', 'Sport'],
  '.activity-card p': [
    'Guided routes through the historic centre and medieval monuments.',
    'Breathtaking city views aboard the cable car.',
    'Walks through Penha Mountain and nearby natural parks.',
    'Museums, galleries and shows all year round.',
    'Traditional pottery, filigree and textiles from Guimarães.',
    'Support Vitória SC in one of the most beautiful stadiums in the country.'
  ],
  '.banner-content h2': '"Portugal was born here"',
  '.banner-content p': 'Guimarães is not just visited — it is felt. Bring the family, your friends, or come alone. You will want to come back.',
  '.banner-content .btn': 'Plan my visit',
  '.food-body p': [
    'Moist inside, golden outside — those who try it once rarely stop at a single slice.',
    'Chickpeas, boiled egg, plenty of olive oil and the soul of Minho cooking. Every tavern has its own version — and all are worth trying.',
    'Fresh, lightly sparkling and produced right next door — the local vinho verde goes with everything, especially Minho fish and seafood.'
  ],
  '.food-tag': ['Pastry', 'Main Course', 'Wines'],
  '.galeria-caption': ['Guimarães Castle', 'Largo da Oliveira', 'Palace of the Dukes', 'Santiago Square', 'Oliveira Church'],
  '.eventos .section-cta a': 'See the full agenda',
  '.hotel-loc': ['📍 Historic Centre', '📍 Castle Hill', '📍 City Centre'],
  '.hotel-body > p:not(.hotel-loc)': [
    'Right on Largo da Oliveira, facing the Collegiate Church. Waking up to that view at breakfast has a price — but it is worth every euro.',
    'Set in a restored medieval monastery right next to the castle, the pousada feels unlike any ordinary hotel.',
    'A good option for travellers on a tighter budget — clean rooms, a great location and the chance to meet other travellers.'
  ],
  '.hotel-card .btn': ['Book', 'Book', 'Book'],
  '.ligacao-body h4': ['Guimarães Town Hall', 'Guimarães Tourism', 'UNESCO – World Heritage', 'Turismo de Portugal', 'Vitória Sport Clube', 'CP – Comboios de Portugal'],
  '.ligacao-body p': [
    'Official municipal portal with services, news and local information.',
    'Official tourism portal with guides, itineraries and an events agenda.',
    'Official UNESCO page on the Historic Centre of Guimarães.',
    'Official Portuguese tourism information about Guimarães and the North region.',
    "Official website of the city's football club, one of the most emblematic in Portugal.",
    'Train timetables and tickets to reach Guimarães from anywhere in the country.'
  ],
  '#cf-assunto option': ['Select a subject…', 'Information request', 'Events and agenda', 'Accommodation', 'Accessible tourism', 'Other'],
  '.form-footer .btn': 'Send Message',
  '#formSuccess': '✅ Message sent successfully! We will get back to you shortly.',
  '#privacidade h4': 'Privacy Policy',
  '#privacidade p': 'The data submitted in this form (name, email, subject and message) is used exclusively to reply to your enquiry and is not shared with third parties. The newsletter subscription stores only your email address and can be cancelled at any time by writing to turismo@cm-guimaraes.pt.',
  '.newsletter-text h3': 'Stay up to date',
  '.newsletter-text p': 'Leave your email and from time to time we will send tips, events and news — no spam, we promise.',
  '.newsletter-form .btn': 'Subscribe',
  '.info-block h4': ['✈️ By Plane', '🚂 By Train', '🚗 By Car', '📞 Guimarães Tourism Office'],
  '.footer-col h5': ['Discover', 'Plan', 'Information'],
  '.footer-col ul li a': ['Guimarães Castle', 'Palace of the Dukes', 'Penha Mountain', 'Historic Centre', 'Museums', 'Accommodation', 'Restaurants', 'How to Get Here', 'Transport', 'Tourist Guides', 'About Guimarães', 'Accessible Tourism', 'Press', 'Privacy Policy', 'Contacts'],
  '.footer-brand p': 'The official tourism portal for the city of Guimarães, a UNESCO World Heritage site and the birthplace of Portugal.',
  '.footer-bottom p': ['© 2026 Visitar Guimarães – Guimarães Town Hall. All rights reserved.', 'Developed with ❤️ to promote tourism in Guimarães.'],
  '#chatStatus': 'Online · AI Guide',
  '#chatGreeting': 'Hello! I am Guigas, the AI tourist guide for Guimarães. Ask me anything about the city!'
};

// Dicionário EN — conteúdos com HTML interno (innerHTML), por seletor
const EN_HTML = {
  "label[for='cf-nome']": 'Full name <span class="req">*</span>',
  "label[for='cf-email']": 'Email address <span class="req">*</span>',
  "label[for='cf-assunto']": 'Subject <span class="req">*</span>',
  "label[for='cf-mensagem']": 'Message <span class="req">*</span>',
  '#privacyLabelText': 'I accept the <a href="#privacidade" class="link-inline">Privacy Policy</a> and authorize the processing of my personal data. <span class="req">*</span>',
  '.form-required-note': '<span class="req">*</span> Required fields',
  '.hotel-price': ['From <strong>95€</strong>/night', 'From <strong>120€</strong>/night', 'From <strong>28€</strong>/night'],
  '.info-block p': [
    'Francisco Sá Carneiro Airport (Porto) – 50 km away. Connection by bus or taxi.',
    'Minho railway line with a direct connection to the city. Station in the urban centre.',
    'Via the A3 (Porto–Braga) + A11 or via the A7. Car parks in the centre.',
    'Praça de Santiago, Historic Centre<br>Tel: +351 253 421 221<br>Email: turismo@cm-guimaraes.pt'
  ]
};

// Dicionário EN — atributos (placeholders), por seletor
const EN_ATTRS = {
  '#chatToggle': { 'data-tooltip': 'Hi! I\'m Guigas 👋', 'aria-label': 'Open chat with Guigas' },
  '#tourismQuery': { placeholder: 'Monuments, events, restaurants…' },
  '#cf-nome': { placeholder: 'Your name' },
  '#cf-email': { placeholder: 'example@email.com' },
  '#cf-mensagem': { placeholder: 'Write your message…' },
  '#newsletterEmail': { placeholder: 'Your email address' },
  '#chatInput': { placeholder: 'Ask me something about Guimarães...' }
};

// Cache dos textos PT originais (preenchida na primeira mudança para EN)
let ptCache = null;

// Guarda os valores PT atuais de todos os seletores dos dicionários
function buildPtCache() {
  ptCache = { texts: {}, html: {}, attrs: {} };
  for (const sel of Object.keys(EN_TEXTS)) {
    ptCache.texts[sel] = [...document.querySelectorAll(sel)].map(e => e.textContent);
  }
  for (const sel of Object.keys(EN_HTML)) {
    ptCache.html[sel] = [...document.querySelectorAll(sel)].map(e => e.innerHTML);
  }
  for (const [sel, attrs] of Object.entries(EN_ATTRS)) {
    ptCache.attrs[sel] = {};
    const el = document.querySelector(sel);
    if (el) for (const a of Object.keys(attrs)) ptCache.attrs[sel][a] = el.getAttribute(a);
  }
}

// Aplica um dicionário (string ou array de strings) aos elementos do seletor
function applyDict(dict, prop) {
  for (const [sel, valor] of Object.entries(dict)) {
    const els = [...document.querySelectorAll(sel)];
    els.forEach((el, i) => {
      const v = Array.isArray(valor) ? valor[i] : (i === 0 ? valor : undefined);
      if (v !== undefined && v !== null) el[prop] = v;
    });
  }
}

// Muda o idioma de toda a página (textos, atributos e dados da API)
function applyLang(lang) {
  if (lang === 'en' && !ptCache) buildPtCache();
  currentLang = lang;
  localStorage.setItem('lang', lang);

  const texts = lang === 'en' ? EN_TEXTS : (ptCache ? ptCache.texts : {});
  const html  = lang === 'en' ? EN_HTML  : (ptCache ? ptCache.html  : {});
  const attrs = lang === 'en' ? EN_ATTRS : (ptCache ? ptCache.attrs : {});
  applyDict(texts, 'textContent');
  applyDict(html, 'innerHTML');
  for (const [sel, mapa] of Object.entries(attrs)) {
    const el = document.querySelector(sel);
    if (el) for (const [a, v] of Object.entries(mapa)) el.setAttribute(a, v);
  }

  // Metadados e controlo do idioma
  document.documentElement.lang = lang === 'en' ? 'en' : 'pt';
  document.title = lang === 'en' ? 'Visit Guimarães – Tourism Portal' : 'Visitar Guimarães – Portal de Turismo';
  const toggle = document.getElementById('langToggle');
  if (toggle) {
    toggle.textContent = lang === 'en' ? 'EN | PT' : 'PT | EN';
    toggle.title = lang === 'en' ? 'Mudar idioma para Português' : 'Switch language to English';
  }

  // Botão "ver todos", cartões dinâmicos e eventos no novo idioma
  const showAllBtn = document.getElementById('showAllPlaces');
  if (showAllBtn) showAllBtn.textContent = showAllPOI ? L('showLess') : L('showAll');
  fetchPlaces(document.getElementById('tourismQuery')?.value.trim() || '');
  fetchEvents();
  if (typeof renderDefaultSuggestions === 'function') renderDefaultSuggestions();
}

// Alternador PT | EN na barra de navegação
document.getElementById('langToggle')?.addEventListener('click', () => {
  applyLang(currentLang === 'pt' ? 'en' : 'pt');
});

// Se o utilizador tinha escolhido inglês numa visita anterior, aplica-o já
if (currentLang === 'en') { currentLang = 'pt'; applyLang('en'); }

/* ============================================================
   EVENTOS — agenda dinâmica ligada a em.guimaraes.pt
   O backend (GET /api/events) extrai os eventos e as datas da
   Agenda Cultural oficial de Guimarães e faz cache de 30 min;
   se a API estiver offline, usa-se a lista local de reserva.
   ============================================================ */

// Eventos locais de reserva (mostrados apenas quando a API está offline)
const FALLBACK_EVENTS = {
  pt: [
    { day: 14, month: 6, month_label: 'Jun', category: 'Festas Religiosas', title: 'Festas Gualterianas', summary: 'As maiores festas de Guimarães, com cortejo histórico, fogo de artifício e animação na cidade.', location: 'Centro Histórico', time: 'Todo o dia', link: 'https://em.guimaraes.pt/' },
    { day: 22, month: 7, month_label: 'Jul', category: 'Música', title: 'GNRation Festival', summary: 'Festival de música contemporânea e artes no espaço cultural GNRation.', location: 'GNRation', time: '21h00', link: 'https://www.gnration.pt/' },
    { day: 5, month: 8, month_label: 'Ago', category: 'Gastronomia', title: 'Feira Medieval de Guimarães', summary: 'Recriação histórica com mercado medieval, espectáculos e gastronomia típica.', location: 'Largo da Oliveira', time: '15h00 – 24h00', link: 'https://em.guimaraes.pt/' },
    { day: 18, month: 9, month_label: 'Set', category: 'Desporto', title: 'Meia Maratona de Guimarães', summary: 'Corrida histórica pelas ruas e monumentos da cidade, aberta a todos os níveis.', location: 'Cidade de Guimarães', time: '09h00', link: 'https://em.guimaraes.pt/' }
  ],
  en: [
    { day: 14, month: 6, month_label: 'Jun', category: 'Religious Festivities', title: 'Gualterianas Festivities', summary: "Guimarães's biggest festivities, with a historical parade, fireworks and entertainment across the city.", location: 'Historic Centre', time: 'All day', link: 'https://em.guimaraes.pt/' },
    { day: 22, month: 7, month_label: 'Jul', category: 'Music', title: 'GNRation Festival', summary: 'Contemporary music and arts festival at the GNRation cultural venue.', location: 'GNRation', time: '9 p.m.', link: 'https://www.gnration.pt/' },
    { day: 5, month: 8, month_label: 'Aug', category: 'Gastronomy', title: 'Guimarães Medieval Fair', summary: 'Historical re-enactment with a medieval market, shows and traditional food.', location: 'Largo da Oliveira', time: '3 p.m. – midnight', link: 'https://em.guimaraes.pt/' },
    { day: 18, month: 9, month_label: 'Sep', category: 'Sport', title: 'Guimarães Half Marathon', summary: 'A historic run through the streets and monuments of the city, open to all levels.', location: 'City of Guimarães', time: '9 a.m.', link: 'https://em.guimaraes.pt/' }
  ]
};

// Constrói o cartão HTML de um evento (mesma estrutura dos cartões estáticos)
function buildEventCard(ev) {
  const card = document.createElement('div');
  card.className = 'event-card';
  const meta = [];
  if (ev.location) meta.push(`<span>📍 ${ev.location}</span>`);
  if (ev.time) meta.push(`<span>🕐 ${ev.time}</span>`);
  card.innerHTML = `
    <div class="event-date">
      <span class="event-day">${String(ev.day || '').padStart(2, '0')}</span>
      <span class="event-month">${ev.month_label || ''}</span>
    </div>
    <div class="event-info">
      <span class="event-cat">${ev.category || L('eventDefaultCat')}</span>
      <h4>${ev.title}</h4>
      ${ev.summary ? `<p>${ev.summary}</p>` : ''}
      ${meta.length ? `<div class="event-meta">${meta.join('')}</div>` : ''}
    </div>
    <a href="${ev.link}" target="_blank" rel="noopener" class="btn btn-sm">${L('eventDetails')}</a>`;
  return card;
}

// Ordena os eventos por proximidade: os próximos primeiro; uma data que
// já passou este ano conta como do próximo ano (vai para o fim da agenda)
function ordenaEventos(lista) {
  const hoje = new Date();
  const inicioHoje = new Date(hoje.getFullYear(), hoje.getMonth(), hoje.getDate());
  const chave = (ev) => {
    if (!ev.month || !ev.day) return Infinity;
    let d = new Date(hoje.getFullYear(), ev.month - 1, ev.day);
    if (d < inicioHoje) d = new Date(hoje.getFullYear() + 1, ev.month - 1, ev.day);
    return d.getTime();
  };
  return [...lista].sort((a, b) => chave(a) - chave(b));
}

// Desenha os eventos na lista da secção Agenda (próximos primeiro, máximo 6)
function renderEvents(lista) {
  const alvo = document.getElementById('eventsList');
  if (!alvo) return;
  alvo.innerHTML = '';
  ordenaEventos(lista).slice(0, 6).forEach(ev => alvo.appendChild(buildEventCard(ev)));
}

// Vai buscar os eventos e as datas reais à Agenda Cultural de Guimarães
// (em.guimaraes.pt, através do backend); em falha usa a lista local
async function fetchEvents() {
  try {
    const r = await fetch(API.events);
    if (!r.ok) throw new Error('API ' + r.status);
    const data = await r.json();
    if (!data.results || !data.results.length) throw new Error('sem eventos');
    renderEvents(data.results);
  } catch (_) {
    renderEvents(FALLBACK_EVENTS[currentLang]);
  }
  // Se o utilizador já escolheu uma data, destaca os eventos correspondentes
  const dataEscolhida = document.getElementById('tourismDate')?.value;
  if (dataEscolhida) destacaEventosNaData(dataEscolhida);
}

// Carrega os eventos reais ao abrir a página
fetchEvents();
